"""add about field to profile

Revision ID: 87de4a9647b1
Revises: b542893669bc
Create Date: 2025-06-29 23:31:53.716792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87de4a9647b1'
down_revision: Union[str, None] = 'b542893669bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_category', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('profile', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'about')
    op.drop_column('blog_category', 'is_published')
    # ### end Alembic commands ###
